name: Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: [ 'ubuntu-latest', 'windows-latest' ]
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        coverage: none
        tools: phpunit:${{ matrix.phpunit-version }}, composer:v2

    - name: Check PHP Version
      run: php -v

    - name: Check Composer Version
      run: composer -V

    - name: Validate composer.json & composer.lock
      run: composer validate --strict

    - name: Install PHP dependencies
      run: composer install --no-interaction --no-progress --no-suggest

    - name: Run Test Suite
      run: vendor/bin/phpunit